### ISSUE TITLE
Upload SBL 1.0.3.RELEASE to Maven Central

### ISSUE THREAD

**Issue by eruiz** [dsyer/spring-boot-legacy#16]
Hi Dave,

I'm trying to use Spring Boot Legacy 1.0.3.RELEASE but it isn't in any of the Maven repositories that I known: Maven Central and Spring IO Repo. However the Spring Boot Legacy 1.0.2.RELEASE is available in these repositories.

The application is based on Spring Boot 1.3, so it seems I should use the Spring Boot Legacy 1.0.3.RELEASE ...

Could you advise which version is the right version for Spring Boot 1.3?

Thanks,

**Comment by eruiz** [comment]
Hi Dave, it would be great if you can upload the SBL 1.0.3.RELEASE to Maven Central.

How can I help to do it?

Thanks in advance,

**Comment by dsyer** [comment]
I don't think there was any change in 1.0.3. I just pushed 1.1.0 (depends on Spring Boot 1.4.2).
