### ISSUE TITLE
Possible bad scm metadata in Maven POM

### ISSUE THREAD

**Issue by ddcruver** [dsyer/spring-boot-legacy#30]
https://github.com/dsyer/spring-boot-legacy/blob/847ebc0484c9cc47f237120c8290cd19de7782e2/spring-boot-legacy/pom.xml#L80-L82

Shouldn't it read more like:
```
	<scm>
		<url>http://github.com/dsyer/spring-boot-legacy</url>
		<connection>scm:git:git://github.com/dsyer/spring-boot-legacy.git</connection>
		<developerConnection>scm:git:ssh://git@github.com/dsyer/spring-boot-legacy.git</developerConnection>
		<tag>HEAD</tag>
	</scm>
```

I see you do have the **dyser** and **scratches** github accounts so maybe part of this is intentional.

**Comment by dsyer** [comment]
Fixed in 5734c3c
