### ISSUE TITLE
Incompatibility with SpringBoot 2.1

### ISSUE THREAD

**Issue by jaro-sagan** [dsyer/spring-boot-legacy#32]
Hi,

In SpringBoot 2.1 the constructor for class `ServletContextInitializerBeans` has been changed by adding varargs `Class<? extends ServletContextInitializer>... initializerTypes`. This change is breaking [this](https://github.com/dsyer/spring-boot-legacy/blob/bfc216fd82360c8b5d4445ea03a2254245723062/spring-boot-legacy/src/main/java/org/springframework/boot/legacy/context/web/NonEmbeddedWebApplicationContext.java#L150) constructor call in spring boot legacy. On compilation time is everything ok (as it should) but on rune time this exception will be thrown

```
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(Lorg/springframework/beans/factory/ListableBeanFactory;)V
	at org.springframework.boot.legacy.context.web.NonEmbeddedWebApplicationContext.getServletContextInitializerBeans(NonEmbeddedWebApplicationContext.java:147) ~[?:?]
	at org.springframework.boot.legacy.context.web.NonEmbeddedWebApplicationContext.selfInitialize(NonEmbeddedWebApplicationContext.java:128) ~[?:?]
	at org.springframework.boot.legacy.context.web.NonEmbeddedWebApplicationContext.init(NonEmbeddedWebApplicationContext.java:87) ~[?:?]
	at org.springframework.boot.legacy.context.web.NonEmbeddedWebApplicationContext.onRefresh(NonEmbeddedWebApplicationContext.java:75) ~[?:?]
	... 51 more
```

There is some byte code dependency on varargs. I have also verified it on simple test case. 

Would it be possible to release spring boot legacy based on SpringBoot 2.1?

**Comment by balaji-tech87** [comment]
Hi ,

I also faced the same error. I raised an error in Spring-boot. They have re-directed me to this location.
https://github.com/spring-projects/spring-boot/issues/16085

Please provide some suggestions.

**Comment by dsyer** [comment]
Please just send a pull request if you have a fix. There is a CLA process but github will tell you.

**Comment by balaji-tech87** [comment]
@dsyer Raised pull request. Please review.

**Comment by dsyer** [comment]
Fixed in #33

**Comment by balaji-tech87** [comment]
@dsyer Any estimate date for 2.1.0 release.

**Comment by dsyer** [comment]
If you test a snapshot and it works we can release now. I haven't tested anything beyond the junit tests here (which are not extensive).

**Comment by balaji-tech87** [comment]
I have done,
Unit testing.
Basic login testing for three samples.
And used this artifact in other app, and the previous error does not occur and app was started successfully.

**Comment by balaji-tech87** [comment]
@dsyer 
I have done,
Unit testing.
Basic login testing for three samples.
And used this artifact in other app, and the previous error does not occur and app was started successfully.

**Comment by balaji-tech87** [comment]
@dsyer Artifact not available in the maven central repository. Any idea, when does the artifact will be uploaded in central repository. (https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-legacy)

**Comment by dsyer** [comment]
It’s there (https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-legacy/2.1.0.RELEASE/). Try again.

**Comment by balaji-tech87** [comment]
@dsyer Yes. Got it . Thanks
